---
- name: Upgrade Junos YOLO
  hosts: all
  roles:
    - Juniper.junos
  vars:
    ansible_python_interpreter: "/opt/ansible/ansible-venv/bin/python"
    netconf_port: 830
    wait_time: 900
  connection: local
  gather_facts: no

  vars_prompt:
    - name: username
      prompt: Junos Username
      private: no
    - name: password
      prompt: Junos Password
      private: yes

  tasks:
    - name: Running Pre-Checks
      juniper_junos_command:
        commands:
          - show bgp summary
          - show interfaces terse
          - show lacp interfaces
          - show lldp neighbors
        format: text
        dest_dir: "./output/pre-checks/"
        return_output: false
        provider:
          host: "{{ ansible_host }}"
          port: 22
          user: "{{ username }}"
          passwd: "{{ password }}"

    - name: Show Device Info
      juniper_junos_facts:  
        host: "{{ inventory_hostname }}"
        savedir: "{{ playbook_dir }}"
        user: "{{ username }}"
        passwd: "{{ password }}"
    - name: Print Model
      debug:
        var: junos.model

    - name: Print Version
      debug:
        var: junos.version


    - name: Copy Junos to QFX5100
      junos_scp:
        host: "{{ inventory_hostname }}"
        src: /opt/ansible/software/jinstall-host-qfx-5-17.4R2-S2.3-signed.tgz
        dest: /var/tmp/
        username: "{{ username }}"
        password: "{{ password }}"
      when:
        - (junos.model == "QFX5100-24Q-2P" or junos.model == "QFX5100-48S-6Q")
        - (junos.version != "17.4R2-S2.3")
        
    - name: Copy Junos to EX4300
      junos_scp:
        host: "{{ inventory_hostname }}"
        src: /opt/ansible/software/jinstall-ex-4300-17.4r2-s2.3-signed.tgz
        dest: /var/tmp/
        username: "{{ username }}"
        password: "{{ password }}"    
      when: 
        - (junos.model == "EX4300-48T")
        - (junos.version != "17.4R2-S2.3")
     
    - block:
      - name: Install Junos OS package QFX5K
        juniper_junos_software:
          version: "17.4R2-S2.3"
          cleanfs: no
          local_package: "/opt/ansible/software/jinstall-host-qfx-5-17.4R2-S2.3-signed.tgz"
          remote_package: "/var/tmp/jinstall-host-qfx-5-17.4R2-S2.3-signed.tgz"
          checksum:
          reboot: true
          validate: false
          logfile: /opt/ansible/logs/{{ inventory_hostname }}-logs.log
          user: "{{ username }}"
          passwd: "{{ password }}"
        register: sw
      - name: Print Response
        debug:
          var: sw
      when:
        - (junos.model == "QFX5100-24Q-2P" or junos.model == "QFX5100-48S-6Q")
        - (junos.version != "17.4R2-S2.3")

    - block:
      - name: Install Junos OS package EX4200
        juniper_junos_software:
          version: "17.4R2-S2.3"
          cleanfs: no
          local_package: "/opt/ansible/software/jinstall-ex-4300-17.4r2-s2.3-signed.tgz"
          remote_package: "/var/tmp/jinstall-ex-4300-17.4r2-s2.3-signed.tgz"
          checksum:
          reboot: true
          validate: false
          force_host: yes
          logfile: /opt/ansible/logs/{{ inventory_hostname }}-logs.log
          user: "{{ username }}"
          passwd: "{{ password }}"
        register: sw
      - name: Print Response
        debug:
          var: sw
      when: 
        - (junos.model == "EX4300-48T")
        - (junos.version != "17.4R2-S2.3")

    - pause:
        prompt: "Pausing for 90 seconds to let devices reboot"
        seconds: 90

    - name: Confirm connectivity is restored
      wait_for: 
        host: "{{ ansible_host }}" 
        port: "{{ netconf_port }}"
        timeout: "{{ wait_time }}"
