---
- name: Begin Copy Process
  juniper_junos_facts:  
    host: "{{ inventory_hostname }}"
    savedir: "{{ playbook_dir }}"
    user: "{{ username }}"
    passwd: "{{ password }}"

- name: Copy Junos to QFX5100
  junos_scp:
    host: "{{ inventory_hostname }}"
    src: /opt/ansible/software/jinstall-host-qfx-5-17.4R2-S4.1-signed.tgz
    dest: /var/tmp/
    username: "{{ username }}"
    password: "{{ password }}"
  when:
    - (junos.model == "QFX5100-24Q-2P" or junos.model == "QFX5100-48S-6Q")
    - (junos.version != "17.4R2-S4.1")
        
- name: Copy Junos to EX4300
  junos_scp:
    host: "{{ inventory_hostname }}"
    src: /opt/ansible/software/jinstall-ex-4300-17.4r2-s2.3-signed.tgz
    dest: /var/tmp/
    username: "{{ username }}"
    password: "{{ password }}"    
  when: 
    - (junos.model == "EX4300-48T")
    - (junos.version != "17.4R2-S3.2")

